package CMS;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public class CreateTable {

    public static void createUsuarioTable() {
        String sql = "CREATE TABLE IF NOT EXISTS Usuario (" +
                "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "nome VARCHAR(255) NOT NULL, " +
                "senha VARCHAR(255) NOT NULL)";
        executeUpdate(sql);
    }

    public static void createConteudoTable() {
        String sql = "CREATE TABLE IF NOT EXISTS Conteudo (" +
                "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "titulo VARCHAR(255) NOT NULL, " +
                "descricao VARCHAR(255) NOT NULL, " +
                "autor_id INT, " +
                "FOREIGN KEY (autor_id) REFERENCES Usuario(id))";
        executeUpdate(sql);
    }

    private static void executeUpdate(String sql) {
        try (Connection conn = DatabaseConnection.getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.executeUpdate(sql);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}